org.joget.marketplace.profilegrid.list.config = Profile Grid List Configuration 
org.joget.marketplace.profilegrid.list.actionsStyle = Row Actions Type 
org.joget.marketplace.profilegrid.list.dd = Dropdown Menu 
org.joget.marketplace.profilegrid.list.nb = Normal Buttons
org.joget.marketplace.profilegrid.list.bottom = Bottom of Row
org.joget.marketplace.profilegrid.list.swipe = Normal Buttons with Swipe Left on Mobile
org.joget.marketplace.profilegrid.list.separator = Separator